import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Sprout,ShoppingBasket,Package,Truck,ChartNoAxesCombined,MessageCircle,LogOut,Plus,ArrowUpRight,MapPin,Users,Sun} from 'lucide-react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const today=()=>new Date().toLocaleDateString('en-CA');
const money=n=>'₹'+Number(n).toLocaleString('en-IN',{maximumFractionDigits:2});
const crops=['Tomato','Onion','Potato','Rice','Chilli','Mango'];
function App(){
 const [session,setSession]=useState(null),[health,setHealth]=useState(null),[view,setView]=useState('Marketplace'),[listings,setListings]=useState([]),[orders,setOrders]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[forecast,setForecast]=useState(null),[crop,setCrop]=useState('Tomato'),[groups,setGroups]=useState([]),[plan,setPlan]=useState(null),[weather,setWeather]=useState(null),[chat,setChat]=useState(null),[language,setLanguage]=useState('English'),[register,setRegister]=useState(false),[matches,setMatches]=useState(null);
 const u=session?.user;
 async function api(path,method='GET',body,token=session?.token){let r;try{r=await fetch(API+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});}catch{throw Error('Cannot reach the API. Start the backend and check VITE_API_URL.')}let d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Check all required fields and values.');return d;}
 async function run(fn){setError('');setNotice('');setBusy(true);try{await fn();}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function refresh(token=session?.token){const [ls,os]=await Promise.all([api('/listings','GET',null,token),api('/orders','GET',null,token)]);setListings(ls);setOrders(os);}
 useEffect(()=>{api('/health').then(setHealth).catch(e=>setError(e.message));},[]);
 async function enter(s){setSession(s);setView(s.user.role==='buyer'?'Marketplace':s.user.role==='farmer'?'Listings':'Overview');setMatches(null);setForecast(null);setPlan(null);setGroups([]);setChat(null);await refresh(s.token);}
 const submit=(fn)=>e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));run(()=>fn(values));};
 async function status(id,s){await api('/orders/'+id+'/status','POST',{status:s});await refresh();setNotice('Order updated.');}
 const nav=u?.role==='buyer'?['Marketplace','Orders','Assistant']:u?.role==='farmer'?['Listings','Orders','Insights','Assistant']:['Overview','Orders','Logistics','Insights','Assistant'];
 const icons={Marketplace:ShoppingBasket,Listings:Sprout,Orders:Package,Overview:ChartNoAxesCombined,Logistics:Truck,Insights:ChartNoAxesCombined,Assistant:MessageCircle};
 const activeOrders=orders.filter(o=>o.status!=='cancelled');
 if(!u)return <div className="auth"><div className="auth-story"><div className="brand"><Sprout size={32}/> AgriNexus</div><span className="eyebrow">GROW LOCAL. TRADE DIRECT.</span><h1>A shorter journey.<br/>A fairer harvest.</h1><p>Connect farmers and FPOs directly with buyers. Coordinate harvests, orders and delivery in one place.</p><div className="auth-foot">SIH26033 <span>Farm → Market → Community</span></div></div><main className="auth-form"><span className="eyebrow">YOUR FARM-TO-MARKET WORKSPACE</span><h2>{register?'Create your account':'Welcome to AgriNexus'}</h2><p>Sign in to start trading directly.</p>{error&&<div role="alert" className="error">{error}</div>}<form onSubmit={submit(async v=>enter(await api('/auth/'+(register?'register':'login'),'POST',v)))}>{register&&<><Field label="Your name / organisation" name="name" required/><label>Account type<select name="role"><option value="farmer">Farmer</option><option value="buyer">Buyer</option></select></label></>}<Field label="Email" name="email" type="email" required/><Field label="Password" name="password" type="password" minLength="8" required/><button disabled={busy}>{register?'Create account':'Sign in'} <ArrowUpRight size={17}/></button></form><button className="link" onClick={()=>setRegister(!register)}>{register?'Already registered? Sign in':'New here? Create an account'}</button>{health?.demo&&<div className="demo"><b>Explore the local demo</b><p>Shared sample accounts. Use only fictional information.</p><div className="row">{['farmer','buyer','admin'].map(r=><button disabled={busy} className="secondary" key={r} onClick={()=>run(async()=>enter(await api('/auth/demo/'+r,'POST')))}>{r==='admin'?'FPO / Admin':r}</button>)}</div></div>}</main></div>;
 return <div className="shell"><aside><div className="brand"><Sprout size={30}/> AgriNexus</div><div className="workspace">{u.role==='admin'?'FPO workspace':u.role+' workspace'}</div><nav>{nav.map(n=>{const Icon=icons[n];return <button className={view===n?'active':''} key={n} onClick={()=>{setView(n);setError('');setNotice('')}}><Icon size={20}/>{n}</button>})}</nav><div className="aside-bottom"><p>Better together.<br/><strong>Closer to the source.</strong></p><button onClick={()=>{setSession(null);setListings([]);setOrders([]);setError('')}}><LogOut size={17}/> Sign out</button></div></aside><div className="content"><header><span>AGRICULTURE, CONNECTED</span><div className="identity"><span className="avatar">{u.name[0]}</span>{u.name}</div></header><main><div className="page-title"><div><span className="eyebrow">{today()} / {u.role.toUpperCase()}</span><h1>{view==='Marketplace'?'Fresh from the farm':view==='Listings'?'Your harvest, your price':view==='Overview'?'A view across your network':view==='Logistics'?'Bring every order closer':view==='Insights'?'Plan the next harvest':view==='Assistant'?'A little help, in your language':'Every order, in one place'}</h1></div><button className="secondary" disabled={busy} onClick={()=>run(()=>refresh())}>Refresh</button></div>{health?.demo&&<div className="banner">Demo workspace · Seeded listings are fictional. Orders are real records in this demo; no payments or deliveries are executed.</div>}{error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="success">{notice}</div>}
 <section className="stats"><Stat label={u.role==='farmer'?'Your active listings':'Available listings'} value={listings.filter(l=>l.quantity>0&&(u.role!=='farmer'||l.farmer_id===u.id)).length} detail="Direct from growers"/><Stat label="Order value" value={money(activeOrders.reduce((a,o)=>a+o.total,0))} detail="Excludes cancelled orders; not payout"/><Stat label="Produce ordered" value={activeOrders.reduce((a,o)=>a+o.quantity,0)+' kg'} detail="Across your visible orders"/></section>
 {(view==='Marketplace'||view==='Listings')&&<><div className="section-head"><h2>{view==='Listings'?'Harvest listings':'Explore produce'}</h2>{view==='Listings'?<button onClick={()=>setSelected({new:true})}><Plus size={18}/> Add harvest</button>:<input aria-label="Search produce" placeholder="Search crop or location…" value={query} onChange={e=>setQuery(e.target.value)}/>}</div>{view==='Marketplace'&&<div className="matchbar"><span>Find a suitable grower</span><select aria-label="Match crop" value={crop} onChange={e=>{setCrop(e.target.value);setMatches(null)}}>{crops.map(c=><option key={c}>{c}</option>)}</select><button className="secondary" disabled={busy} onClick={()=>run(async()=>setMatches(await api('/matches?crop='+crop+'&quantity=1&lat=17.44&lon=78.49')))}>Match near Hyderabad</button>{matches&&<button className="link" onClick={()=>setMatches(null)}>Clear</button>}</div>}{matches&&<p className="muted">Ranked for 1 kg by produce cost + illustrative ₹5/km distance weight. Not a delivery quote.</p>}<div className="grid">{(matches||listings).filter(l=>(view!=='Listings'||l.farmer_id===u.id)&&(!query||[l.crop,l.location].join(' ').toLowerCase().includes(query.toLowerCase()))).map(l=><article className="produce" key={l.id}><div className={'produce-band '+l.crop.toLowerCase()}><Sprout size={38}/><span>DIRECT FROM FARM</span></div><div className="produce-body"><div className="row between"><h2>{l.crop}</h2><span className="pill">{l.quantity>0?'Available':'Sold out'}</span></div><p>{l.farmer}</p><p className="location"><MapPin size={15}/>{l.location}{l.distance_km!=null&&' · '+l.distance_km+' km'}</p><div className="row between"><strong className="price">{money(l.price)}<small>/kg</small></strong><span>{l.quantity} kg left</span></div><div className="card-bottom"><span>Harvest {l.harvest_date}</span>{u.role==='buyer'&&<button disabled={!l.quantity} onClick={()=>setSelected(l)}>Order <ArrowUpRight size={16}/></button>}</div></div></article>)}</div>{!listings.length&&<Empty text="No produce yet. Farmers can add the first harvest."/>}</>}
 {view==='Orders'&&<section className="panel"><h2>Order activity</h2>{!orders.length?<Empty text="No orders yet. Buyers can place an order from Marketplace."/>:<div className="table-wrap"><table><thead><tr><th>Crop / order</th><th>Trading partner</th><th>Quantity</th><th>Value</th><th>Delivery</th><th>Status / action</th></tr></thead><tbody>{[...orders].reverse().map(o=><tr key={o.id}><td><b>{o.crop}</b><small>{o.id.slice(0,8)}</small></td><td>{u.role==='buyer'?o.farmer:o.buyer}</td><td>{o.quantity} kg</td><td>{money(o.total)}</td><td>{o.delivery_date}<small>{o.address}</small></td><td><span className="pill">{o.status}</span><div className="actions">{u.role!=='buyer'&&o.status==='placed'&&<button disabled={busy} onClick={()=>run(()=>status(o.id,'accepted'))}>Accept</button>}{u.role!=='buyer'&&o.status==='accepted'&&<button disabled={busy} onClick={()=>run(()=>status(o.id,'dispatched'))}>Dispatch</button>}{u.role!=='buyer'&&o.status==='dispatched'&&<button disabled={busy} onClick={()=>run(()=>status(o.id,'delivered'))}>Delivered</button>}{['placed','accepted'].includes(o.status)&&<button className="link" disabled={busy} onClick={()=>run(()=>status(o.id,'cancelled'))}>Cancel</button>}</div></td></tr>)}</tbody></table></div>}</section>}
 {view==='Overview'&&<section className="panel"><div className="section-head"><div><h2>Consolidate your demand</h2><p>Group pending orders by crop and delivery day.</p></div><button disabled={busy} onClick={()=>run(async()=>setGroups(await api('/aggregation')))}>Group orders</button></div>{groups.length?groups.map(g=><div className="group" key={g.group}><Users/><b>{g.group}</b><span>{g.kg} kg</span><span>{g.orders} orders · {g.farmers} farmers</span></div>):<Empty text="Group orders to see consolidated quantities for your network."/>}<p className="muted">Accept orders in Orders, then open Logistics to plan pickups and deliveries.</p></section>}
 {view==='Logistics'&&<section className="panel"><h2>Pickup & delivery planner</h2><p>Plans accepted orders for the selected date, with a shared FPO depot.</p><form className="inline-form" onSubmit={submit(async v=>setPlan(await api('/routes','POST',{...v,capacity_kg:+v.capacity_kg,vehicles:+v.vehicles,depot_lat:+v.depot_lat,depot_lon:+v.depot_lon})))}><Field label="Delivery date" name="delivery_date" type="date" defaultValue={today()} required/><Field label="Vehicle capacity (kg)" name="capacity_kg" type="number" min="1" max="100000" defaultValue="1500" required/><Field label="Available vehicles" name="vehicles" type="number" min="1" max="10" defaultValue="3" required/><Field label="Depot latitude" name="depot_lat" type="number" step="any" min="-90" max="90" defaultValue="17.63" required/><Field label="Depot longitude" name="depot_lon" type="number" step="any" min="-180" max="180" defaultValue="78.48" required/><button disabled={busy}>Plan deliveries</button></form>{plan&&<><p className="banner">{plan.message}</p>{!!plan.routes.length&&<RouteMap routes={plan.routes}/ >}{plan.routes.map(r=><div className="route" key={r.vehicle}><h3>Vehicle {r.vehicle} · {r.km} km estimated</h3><ol>{r.stops.map((s,i)=><li key={i}>{s.label} {s.change_kg!==0&&<b>({s.change_kg>0?'+':''}{s.change_kg} kg)</b>}</li>)}</ol></div>)}</>}</section>}
 {view==='Insights'&&<div className="insights"><section className="panel"><h2>Demand outlook</h2><p>Forecast from your marketplace’s order history.</p><div className="row"><select aria-label="Forecast crop" value={crop} onChange={e=>{setCrop(e.target.value);setForecast(null)}}>{crops.map(c=><option key={c}>{c}</option>)}</select><button disabled={busy} onClick={()=>run(async()=>setForecast(await api('/forecast?crop='+crop)))}>Calculate</button></div>{forecast&&(forecast.ready?<><p>{forecast.method}</p><p>Holdout error: <b>{forecast.mae_kg} kg/day</b></p><div className="bars">{forecast.forecast.map(d=><div key={d.date}><span>{d.date.slice(5)}</span><i style={{width:Math.max(2,d.kg/Math.max(1,...forecast.forecast.map(x=>x.kg))*65)+'%'}}/><b>{d.kg} kg</b></div>)}</div><h3>Next-day price estimate: {money(forecast.price_baseline)}/kg</h3><p className="muted">{forecast.price_method}. Forecast quality is not validated on external market data.</p></>:<Empty text={forecast.message}/>)}</section><section className="panel"><Sun size={30}/><h2>Medchal weather</h2><p>Current conditions at the default FPO location.</p><button className="secondary" disabled={busy} onClick={()=>run(async()=>setWeather(await api('/weather')))}>Check weather</button>{weather&&(weather.available?<h3>{weather.temperature}°C · {weather.description}</h3>:<p>{weather.message}</p>)}</section></div>}
 {view==='Assistant'&&<section className="panel assistant"><MessageCircle size={36}/><h2>Ask AgriNexus</h2><p>Help with selling, buying and coordinating produce. The assistant cannot place orders or change prices.</p><form onSubmit={submit(async v=>setChat(await api('/chat','POST',{message:v.message,language})))}><label>Reply language<select value={language} onChange={e=>setLanguage(e.target.value)}>{['English','Telugu','Hindi'].map(l=><option key={l}>{l}</option>)}</select></label><label>Your question<textarea name="message" maxLength="1500" rows="4" placeholder="How do I sell my harvest?" required/></label><button disabled={busy}>{busy?'Working…':'Ask assistant'}</button></form>{chat&&<div className="answer"><span className="eyebrow">{chat.source}</span><p>{chat.reply}</p></div>}</section>}
 <footer>AgriNexus · Direct trade, shared growth <span>SIH26033 prototype</span></footer></main></div>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-label={selected.new?'Add harvest':'Place order'} onClick={e=>e.stopPropagation()}><div className="section-head"><h2>{selected.new?'List your harvest':'Order '+selected.crop}</h2><button aria-label="Close" className="secondary" onClick={()=>setSelected(null)}>✕</button></div>{error&&<div role="alert" className="error">{error}</div>}<form onSubmit={submit(async v=>{if(selected.new){await api('/listings','POST',{...v,quantity:+v.quantity,price:+v.price,lat:+v.lat,lon:+v.lon});setNotice('Your harvest is listed.')}else{await api('/orders','POST',{...v,listing_id:selected.id,quantity:+v.quantity,lat:+v.lat,lon:+v.lon});setNotice('Order placed. Track it in Orders.')}setSelected(null);await refresh();})}>{selected.new?<><label>Crop<select name="crop">{crops.map(c=><option key={c}>{c}</option>)}</select></label><Field label="Price per kg (₹)" name="price" type="number" min="0.01" max="100000" step="0.01" required/><Field label="Farm location" name="location" required/><Field label="Harvest date" name="harvest_date" type="date" defaultValue={today()} required/></>:<><p>{money(selected.price)} per kg · {selected.quantity} kg available. Delivery charges and payment are arranged outside this prototype.</p><Field label="Delivery address" name="address" required minLength="5"/><Field label="Delivery date" name="delivery_date" type="date" min={today()} defaultValue={today()} required/></>}<Field label="Quantity (kg)" name="quantity" type="number" min="1" max={selected.new?100000:selected.quantity} required/><div className="row"><Field label={selected.new?'Farm latitude':'Delivery latitude'} name="lat" type="number" step="any" min="-90" max="90" defaultValue="17.54" required/><Field label={selected.new?'Farm longitude':'Delivery longitude'} name="lon" type="number" step="any" min="-180" max="180" defaultValue="78.49" required/></div><button disabled={busy}>{busy?'Saving…':selected.new?'Publish listing':'Confirm order'}</button></form></section></div>}</div>
}
function Field({label,...props}){return <label>{label}<input {...props}/></label>}
function Stat({label,value,detail}){return <article><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Empty({text}){return <div className="empty"><Sprout size={30}/><p>{text}</p></div>}
function RouteMap({routes}){const ref=useRef();useEffect(()=>{const map=L.map(ref.current).setView([17.55,78.49],11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',maxZoom:19}).addTo(map);const bounds=[];routes.forEach((r,j)=>{const points=r.stops.map(s=>[s.lat,s.lon]);bounds.push(...points);L.polyline(points,{color:['#176743','#d18424','#436ec1'][j%3],dashArray:'6,6'}).addTo(map);r.stops.forEach((s,i)=>{const text=document.createElement('span');text.textContent=(i+1)+'. '+s.label;L.circleMarker([s.lat,s.lon],{radius:6,color:'#176743',fillOpacity:1}).bindPopup(text).addTo(map)})});if(bounds.length)map.fitBounds(bounds,{padding:[30,30]});return()=>map.remove()},[routes]);return <div ref={ref} className="map" aria-label="Delivery stops on OpenStreetMap"/>}
createRoot(document.getElementById('root')).render(<App/>);
